name: auto_greet_instagram
description: A personal automation app that sends scheduled greeting messages to Instagram friends.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - logo.png

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "logo.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: logo.png
  android: true
  ios: false
  android_12:
    image: logo.png
    color: "#FFFFFF"
